name: Deploy Linuxo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deployment files
        run: |
          mkdir deploy

          rsync -av . deploy/ \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='docs/' \
            --exclude='node_modules/' \
            --exclude='.env' \
            --exclude='*.log' \
            --exclude='deploy/'

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ .SFTP_PORT }}
          local_path: './deploy/*'
          remote_path: './'
          sftp_only: true